trigger:
  branches:
    include:
    - master
  tags:
    include:
    - ^v\d+\.\d+(\.\d+)?(-\S*)?$

pr:
- master

resources:
  repositories:
  - repository: azure_template
    type: github
    name: mdolab/.github
    endpoint: mdolab

variables:
- name: REPO_NAME
  value: sphinx_mdolab_theme
- name: TEST_REPO
  value: pyhyp

stages:
- stage: Test
  dependsOn: []
  displayName: Test
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-20.04'
    strategy:
      matrix:
        'python37':
          PYTHON_VERSION: '3.7'
        'python38':
          PYTHON_VERSION: '3.8'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - script: pip install .
      displayName: Install
    - script: |
        git clone https://github.com/mdolab/${{ variables.TEST_REPO }}.git
        cd ${{ variables.TEST_REPO }}/doc
        pip install -r requirements.txt
      displayName: Set Up Test Repo
    - script: make html
      displayName: Test Making Docs

- stage: Style
  dependsOn: []
  displayName: Style
  jobs:
  - template: azure/azure_style.yaml@azure_template
    parameters:
      REPO_NAME: ${{ variables.REPO_NAME }}
      IGNORE_STYLE: false

- stage:
  dependsOn: 
  - Test
  - Style
  displayName: PyPI
  condition: and(succeeded(), contains(variables['build.sourceBranch'], 'tags'))
  jobs:
  - template: azure/azure_pypi.yaml@azure_template
    parameters:
      REPO_NAME: ${{ variables.REPO_NAME }}
