os: linux
language: python
python:
    - "3.7"
install: skip

script: skip

deploy:
  provider: pypi
  user: "__token__"
  password: "$PYPI_TOKEN"
  distributions: "sdist bdist_wheel" 
  on:
    tags: true
  skip_existing: true
