os: linux
language: python
env:
  - TEST_REPO=pyhyp
python:
  - "3.7"

install: pip install .

script:
  - git clone https://github.com/mdolab/$TEST_REPO.git
  - cd $TEST_REPO/doc
  - make html

deploy:
  provider: pypi
  user: "__token__"
  password: "$PYPI_TOKEN"
  distributions: "sdist bdist_wheel" 
  on:
    tags: true
  skip_existing: true
